<?php

/**
 * @file
 * Contains tfg.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tfg_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tfg module.
    case 'help.page.tfg':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Compile Gatsby on hook save') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tfg_theme() {
  return [
    'tfg' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_entity_view().
 */
function tfg_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

}

/**
 * Implements hook_entity_update().
 */
function tfg_entity_update(Drupal\Core\Entity\EntityInterface $entity) {

  $handle = curl_init();

  $url = "172.22.0.7:3000/compilar";

  curl_setopt($handle, CURLOPT_PORT, 3000);
  // Set the url

  curl_setopt($handle, CURLOPT_URL, $url);

  // Set the result output to be a string.
  curl_setopt($handle, CURLOPT_RETURNTRANSFER, TRUE);

  //url_setopt ($handle, CURLOPT_PORT , 3000);
  $output = curl_exec($handle);

  curl_close($handle);

  echo $output;
  drupal_set_message($output);

}

function tfg_views_post_execute(ViewExecutable $view) {
/*
  $handle = curl_init();

  $url = "172.22.0.7:3000/compilar";

  curl_setopt($handle, CURLOPT_PORT, 3000);
  // Set the url

  curl_setopt($handle, CURLOPT_URL, $url);

  // Set the result output to be a string.
  curl_setopt($handle, CURLOPT_RETURNTRANSFER, TRUE);

  //url_setopt ($handle, CURLOPT_PORT , 3000);
  $output = curl_exec($handle);

  curl_close($handle);

  echo $output;
  drupal_set_message($output);
*/
}


