<?php

/**
 * @file
 * Contains conversion.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function conversion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the conversion module.
    case 'help.page.conversion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function conversion_theme($existing, $type, $theme, $path) {
  return [
    'conversion' => [
      'render element' => 'children',
    ],
  ];
}
